//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zxcvbn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeedbackResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeedbackResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zxcvbn.FeedbackResources", typeof(FeedbackResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-uppercase is almost as easy to guess as all-lowercase.
        /// </summary>
        internal static string AllUppercas {
            get {
                return ResourceManager.GetString("AllUppercas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid dates and years that are associated with you.
        /// </summary>
        internal static string AvoidAssociatedDates {
            get {
                return ResourceManager.GetString("AvoidAssociatedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid years that are associated with you.
        /// </summary>
        internal static string AvoidAssociatedYears {
            get {
                return ResourceManager.GetString("AvoidAssociatedYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid recent years.
        /// </summary>
        internal static string AvoidRecentYears {
            get {
                return ResourceManager.GetString("AvoidRecentYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid repeated words and characters.
        /// </summary>
        internal static string AvoidRepeats {
            get {
                return ResourceManager.GetString("AvoidRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalization doesn&apos;t help very much.
        /// </summary>
        internal static string Capitalization {
            get {
                return ResourceManager.GetString("Capitalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common names and surnames are easy to guess.
        /// </summary>
        internal static string CommonNames {
            get {
                return ResourceManager.GetString("CommonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates are often easy to guess.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a few words, avoid common phrases.
        /// </summary>
        internal static string Default1 {
            get {
                return ResourceManager.GetString("Default1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need for symbols, digits, or uppercase letters.
        /// </summary>
        internal static string Default2 {
            get {
                return ResourceManager.GetString("Default2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another word or two, uncommon words are better.
        /// </summary>
        internal static string ExtraFeedback {
            get {
                return ResourceManager.GetString("ExtraFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats like &apos;abcabcabc&apos; are only slightly harder to guess than &apos;abc&apos;.
        /// </summary>
        internal static string GroupRepeats {
            get {
                return ResourceManager.GetString("GroupRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight rows of keys are easy to guess.
        /// </summary>
        internal static string KeyRows {
            get {
                return ResourceManager.GetString("KeyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names and surnames by themselves are easy to guess.
        /// </summary>
        internal static string NamesThemselves {
            get {
                return ResourceManager.GetString("NamesThemselves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent years are easy to guess.
        /// </summary>
        internal static string RecentYears {
            get {
                return ResourceManager.GetString("RecentYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed words aren&apos;t much harder to guess.
        /// </summary>
        internal static string ReversedWords {
            get {
                return ResourceManager.GetString("ReversedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short keyboard patterns are easy to guess.
        /// </summary>
        internal static string ShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("ShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is similar to a commonly used password.
        /// </summary>
        internal static string SimilarToCommon {
            get {
                return ResourceManager.GetString("SimilarToCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats like &apos;aaa&apos; are easy to guess.
        /// </summary>
        internal static string SingleRepeats {
            get {
                return ResourceManager.GetString("SingleRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictable substitutions like &apos;@&apos; instead of &apos;a&apos; don&apos;t help very much.
        /// </summary>
        internal static string Substitutions {
            get {
                return ResourceManager.GetString("Substitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a top-10 common password.
        /// </summary>
        internal static string Top10 {
            get {
                return ResourceManager.GetString("Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a top-100 common password.
        /// </summary>
        internal static string Top100 {
            get {
                return ResourceManager.GetString("Top100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a longer keyboard pattern with more turns.
        /// </summary>
        internal static string UseLongerPattern {
            get {
                return ResourceManager.GetString("UseLongerPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a very common password.
        /// </summary>
        internal static string VeryCommon {
            get {
                return ResourceManager.GetString("VeryCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A word by itself is easy to guess.
        /// </summary>
        internal static string WordItselft {
            get {
                return ResourceManager.GetString("WordItselft", resourceCulture);
            }
        }
    }
}
